import { useEffect, useState } from "react";
import { useLocation, useNavigate, useParams } from "react-router-dom";
import MarketplaceHeader from "../components/MarketplaceHeader";
import { BuyerAddresses as Addresses, BuyerProfileSettings as Profile } from "../components/BuyerLocationSettings";
import { authAPI, buyerAPI, notificationAPI } from "../api/api";
import { useAuth } from "../context/AuthContext";
import { useToast } from "../context/ToastContext";

const NAV = [["", "Overview"], ["profile", "Profile"], ["addresses", "Addresses"], ["rfps", "My RFPs"], ["quotes", "Quotes"], ["saved", "Saved"], ["notifications", "Notifications"], ["security", "Login & security"]];
const blankAddress = { label: "Office", contact_name: "", phone: "", line1: "", line2: "", city: "", state: "", postal_code: "", country: "India", is_default: false };

export default function BuyerAccount() {
  const location = useLocation(); const navigate = useNavigate(); const { id } = useParams(); const { user, logout } = useAuth(); const toast = useToast(); const section = location.pathname.split("/")[2] || "";
  return <div className="market-page account-page"><MarketplaceHeader compact /><main className="account-shell"><aside className="account-sidebar"><div className="account-welcome"><span>{user?.name?.[0]}</span><small>Hello,</small><b>{user?.name}</b></div><nav>{NAV.map(([key, label]) => <button key={key} className={section === key ? "active" : ""} onClick={() => navigate(`/account${key ? `/${key}` : ""}`)}>{label}<span>›</span></button>)}</nav></aside><section className="account-content">{section === "" && <Overview navigate={navigate} />}{section === "profile" && <Profile toast={toast} />}{section === "addresses" && <Addresses toast={toast} />}{section === "rfps" && (id ? <RfpDetail id={id} navigate={navigate} /> : <Rfps navigate={navigate} toast={toast} />)}{section === "quotes" && <Quotes navigate={navigate} />}{section === "saved" && <Saved navigate={navigate} toast={toast} />}{section === "notifications" && <Notifications navigate={navigate} toast={toast} />}{section === "security" && <Security logout={logout} toast={toast} />}</section></main></div>;
}

function Title({ eyebrow, children, action }) { return <div className="account-title"><div><span>{eyebrow}</span><h1>{children}</h1></div>{action}</div>; }
function LoadingState({ label = "Loading your account…" }) { return <div className="account-loading"><i className="page-spinner" /><b>{label}</b><small>Your data is safe while this loads.</small></div>; }
function ErrorState({ message, retry }) { return <div className="account-error"><b>Something went wrong</b><p>{message}</p><button onClick={retry}>Try again</button></div>; }
function Modal({ title, children, onClose, danger = false }) { return <div className="account-modal-backdrop" role="presentation" onMouseDown={event => event.target === event.currentTarget && onClose()}><section className={`account-modal ${danger ? "danger" : ""}`} role="dialog" aria-modal="true" aria-labelledby="account-modal-title"><header><div><span>{danger ? "IMPORTANT ACTION" : "ACCOUNT SECURITY"}</span><h2 id="account-modal-title">{title}</h2></div><button onClick={onClose} aria-label="Close dialog">×</button></header>{children}</section></div>; }

function useLoad(loader, dependencies = []) {
  const [state, setState] = useState({ loading: true, error: "", data: null });
  const load = () => { setState(current => ({ ...current, loading: true, error: "" })); loader().then(data => setState({ loading: false, error: "", data })).catch(error => setState({ loading: false, error: error.response?.data?.detail || "Could not load this section.", data: null })); };
  useEffect(() => { load(); }, dependencies);
  return [state, load, setState];
}

function Overview({ navigate }) {
  const [state, reload] = useLoad(() => Promise.all([buyerAPI.getMyRequests(), buyerAPI.quotes(), buyerAPI.saved()]).then(([r, q, s]) => ({ requests: r.data, quotes: q.data, saved: s.data })), []);
  if (state.loading) return <LoadingState />; if (state.error) return <ErrorState message={state.error} retry={reload} />;
  return <><Title eyebrow="YOUR BUYER ACCOUNT">Account overview</Title><div className="account-stat-grid"><button onClick={() => navigate("/account/rfps")}><strong>{state.data.requests.length}</strong><span>Requirements</span></button><button onClick={() => navigate("/account/quotes")}><strong>{state.data.quotes.length}</strong><span>Quotes received</span></button><button onClick={() => navigate("/account/saved")}><strong>{state.data.saved.length}</strong><span>Saved items</span></button></div><div className="account-panel"><h2>Quick actions</h2><div className="quick-actions"><button onClick={() => navigate("/search")}>Find a service</button><button onClick={() => navigate("/account/rfps?new=1")}>Create an RFP</button><button onClick={() => navigate("/messages")}>Open messages</button><button onClick={() => navigate("/account/addresses")}>Manage addresses</button></div></div></>;
}

function LegacyProfile({ toast }) {
  const [form, setForm] = useState({ organization_name: "", company_type: "", sector: "", annual_procurement_budget_band: "", preferred_vendor_categories: "", phone: "", website: "", location: "" }); const [saving, setSaving] = useState(false);
  const [state, reload] = useLoad(() => buyerAPI.getMyProfile().then(r => r.data || {}), []);
  useEffect(() => { if (state.data) setForm(current => ({ ...current, ...state.data })); }, [state.data]);
  const save = async event => { event.preventDefault(); setSaving(true); try { await buyerAPI.updateProfile(form); toast.success("Buyer profile saved"); } catch (error) { toast.error(error.response?.data?.detail || "Could not save profile"); } finally { setSaving(false); } };
  if (state.loading) return <LoadingState label="Loading your profile…" />; if (state.error) return <ErrorState message={state.error} retry={reload} />;
  const fields = [["organization_name", "Organisation name"], ["company_type", "Company type"], ["sector", "Sector"], ["annual_procurement_budget_band", "Annual procurement budget"], ["preferred_vendor_categories", "Preferred vendor categories"], ["phone", "Contact number"], ["website", "Website"], ["location", "Primary service region"]];
  return <><Title eyebrow="ACCOUNT SETTINGS">Buyer profile</Title><p className="account-intro">These details help prefill requirements and suggest relevant service regions. Nothing here is published as a vendor listing.</p><form className="account-form" onSubmit={save}>{fields.map(([key, label]) => <label key={key}><span>{label}</span><input value={form[key] || ""} onChange={e => setForm({ ...form, [key]: e.target.value })} /></label>)}<button className="primary-action" disabled={saving}>{saving ? "Saving profile…" : "Save profile"}</button></form></>;
}

function LegacyAddresses({ toast }) {
  const [form, setForm] = useState(null); const [saving, setSaving] = useState(false); const [state, reload] = useLoad(() => buyerAPI.addresses().then(r => r.data), []); const items = state.data || [];
  const save = async event => { event.preventDefault(); setSaving(true); try { await buyerAPI.addAddress(form); setForm(null); reload(); toast.success("Address saved"); } catch (error) { toast.error(error.response?.data?.detail || "Could not save address"); } finally { setSaving(false); } };
  if (state.loading) return <LoadingState label="Loading saved addresses…" />; if (state.error) return <ErrorState message={state.error} retry={reload} />;
  return <><Title eyebrow="CONTACT & LOCATION" action={<button className="primary-action" onClick={() => setForm({ ...blankAddress })}>Add address</button>}>Saved addresses</Title><p className="account-intro">Use addresses to prefill delivery and service locations in new requirements.</p>{form && <form className="account-form address-form" onSubmit={save}>{Object.keys(blankAddress).filter(key => key !== "is_default").map(key => <label key={key}><span>{key.replaceAll("_", " ")}</span><input required={key !== "line2"} value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })} /></label>)}<label className="checkbox-field"><input type="checkbox" checked={form.is_default} onChange={e => setForm({ ...form, is_default: e.target.checked })} /><span>Use as default procurement address</span></label><div className="form-actions"><button type="button" onClick={() => setForm(null)}>Cancel</button><button className="primary-action" disabled={saving}>{saving ? "Saving…" : "Save address"}</button></div></form>}<div className="address-grid">{items.map(item => <article key={item.id}><div><b>{item.label}</b>{item.is_default && <span>Default</span>}</div><strong>{item.contact_name}</strong><p>{item.line1}{item.line2 ? `, ${item.line2}` : ""}<br />{item.city}, {item.state} {item.postal_code}<br />{item.phone}</p><footer>{!item.is_default && <button onClick={() => buyerAPI.defaultAddress(item.id).then(() => { reload(); toast.success("Default address updated"); })}>Make default</button>}<button onClick={() => buyerAPI.deleteAddress(item.id).then(() => { reload(); toast.success("Address removed"); }).catch(error => toast.error(error.response?.data?.detail || "Could not remove address"))}>Remove</button></footer></article>)}{!items.length && !form && <div className="account-empty">No saved addresses yet.</div>}</div></>;
}

function Rfps({ navigate, toast }) {
  const search = new URLSearchParams(window.location.search); const [showNew, setShowNew] = useState(search.get("new") === "1"); const [saving, setSaving] = useState(false); const [form, setForm] = useState({ title: "", description: "", category: "", location: "", budget: "", service_id: search.get("service") ? Number(search.get("service")) : null }); const [state, reload] = useLoad(() => buyerAPI.getMyRequests().then(r => r.data), []); const items = state.data || [];
  const create = async event => { event.preventDefault(); setSaving(true); try { await buyerAPI.createRequest(form); setShowNew(false); reload(); toast.success("RFP published"); } catch (error) { toast.error(error.response?.data?.detail || "Could not publish RFP"); } finally { setSaving(false); } };
  if (state.loading) return <LoadingState label="Loading your requirements…" />; if (state.error) return <ErrorState message={state.error} retry={reload} />;
  return <><Title eyebrow="PROCUREMENT" action={<button className="primary-action" onClick={() => setShowNew(true)}>Create RFP</button>}>My requirements</Title>{showNew && <form className="account-form" onSubmit={create}><label><span>Requirement title</span><input required value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} /></label><label className="wide"><span>Description</span><textarea required value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /></label>{["category", "location", "budget"].map(key => <label key={key}><span>{key}</span><input value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })} /></label>)}<div className="form-actions"><button type="button" onClick={() => setShowNew(false)}>Cancel</button><button className="primary-action" disabled={saving}>{saving ? "Publishing…" : "Publish RFP"}</button></div></form>}<div className="account-list">{items.map(item => <button key={item.id} onClick={() => navigate(`/account/rfps/${item.id}`)}><div><b>{item.title}</b><small>{item.category || "General procurement"} · {item.location || "Any location"}</small></div><span className={`status-pill ${item.status}`}>{item.status}</span><strong>{item.bid_count} quotes</strong><i>›</i></button>)}{!items.length && <div className="account-empty">You have not created an RFP yet.</div>}</div></>;
}

function RfpDetail({ id, navigate }) {
  const [state, reload] = useLoad(() => Promise.all([buyerAPI.getRequest(id), buyerAPI.getBidsOnRequest(id)]).then(([rfp, bids]) => ({ rfp: rfp.data, bids: bids.data })), [id]);
  if (state.loading) return <LoadingState label="Opening requirement and quotes…" />; if (state.error) return <ErrorState message={state.error} retry={reload} />; const { rfp, bids } = state.data;
  return <><button className="back-link" onClick={() => navigate("/account/rfps")}>← My RFPs</button><Title eyebrow={rfp.status}>{rfp.title}</Title><div className="rfp-summary"><p>{rfp.description}</p><span>{rfp.category || "General"}</span><span>{rfp.location || "Any location"}</span><span>{rfp.budget || "Budget not specified"}</span></div><h2 className="subheading">Quotes from vendors</h2><div className="quote-grid">{bids.map(bid => <article key={bid.id}><div className="quote-vendor"><span>{bid.vendor_name?.[0]}</span><div><b>{bid.vendor_name}</b><small>{bid.vendor_location}</small></div></div><strong className="quote-price">{bid.proposed_price || "Price on discussion"}</strong><p>{bid.cover_note}</p><div className="vendor-contact"><b>Matched-bid contact</b><span>{bid.vendor_email}</span><span>{bid.vendor_phone || "Phone not shared"}</span></div>{bid.conversation_id && <button className="primary-action" onClick={() => navigate(`/messages/${bid.conversation_id}`)}>Message vendor</button>}</article>)}{!bids.length && <div className="account-empty">No quotes received yet.</div>}</div></>;
}

function Quotes({ navigate }) { const [state, reload] = useLoad(() => buyerAPI.quotes().then(r => r.data), []); if (state.loading) return <LoadingState label="Loading vendor quotes…" />; if (state.error) return <ErrorState message={state.error} retry={reload} />; return <><Title eyebrow="VENDOR RESPONSES">Quotes received</Title><div className="quote-grid">{state.data.map(item => <article key={item.id}><b>{item.vendor_name}</b><small>{item.request_title}</small><strong className="quote-price">{item.proposed_price || "Price on discussion"}</strong><p>{item.cover_note}</p>{item.conversation_id && <button className="primary-action" onClick={() => navigate(`/messages/${item.conversation_id}`)}>Open conversation</button>}</article>)}{!state.data.length && <div className="account-empty">No vendor quotes yet.</div>}</div></>; }

function Saved({ navigate, toast }) { const [state, reload] = useLoad(() => buyerAPI.saved().then(r => r.data), []); if (state.loading) return <LoadingState label="Loading saved services…" />; if (state.error) return <ErrorState message={state.error} retry={reload} />; return <><Title eyebrow="SHORTLIST">Saved services & vendors</Title><div className="saved-grid">{state.data.map(item => <article key={item.id} onClick={() => item.target_type === "service" && navigate(`/services/${item.target_id}`)}><div className="saved-thumb">{item.title[0]}</div><div><span>{item.target_type}</span><b>{item.title}</b><small>{item.subtitle}</small></div><button onClick={event => { event.stopPropagation(); buyerAPI.unsave(item.target_type, item.target_id).then(() => { reload(); toast.success("Removed from saved items"); }); }}>Remove</button></article>)}{!state.data.length && <div className="account-empty">Nothing saved yet. Use the heart on any service.</div>}</div></>; }

function Notifications({ navigate, toast }) {
  const [state, reload, setState] = useLoad(() => notificationAPI.getAll().then(r => ({ items: r.data?.notifications || [], unread: r.data?.unread_count || 0 })), []); const data = state.data || { items: [], unread: 0 };
  const updateItem = id => setState(current => ({ ...current, data: { unread: Math.max(0, current.data.unread - (current.data.items.find(item => item.id === id)?.is_read ? 0 : 1)), items: current.data.items.map(item => item.id === id ? { ...item, is_read: true } : item) } }));
  if (state.loading) return <LoadingState label="Loading notifications…" />; if (state.error) return <ErrorState message={state.error} retry={reload} />;
  return <><Title eyebrow="UPDATES" action={data.unread > 0 && <button className="secondary-action" onClick={() => notificationAPI.markAllRead().then(() => { setState(current => ({ ...current, data: { unread: 0, items: current.data.items.map(item => ({ ...item, is_read: true })) } })); toast.success("All notifications marked read"); })}>Mark all read</button>}>Notifications</Title><p className="account-intro">{data.unread ? `${data.unread} unread update${data.unread === 1 ? "" : "s"}` : "You are all caught up."}</p><div className="notification-list">{data.items.map(item => <article className={item.is_read ? "" : "unread"} key={item.id}><span className={`notification-dot ${item.type}`} /><button className="notification-content" onClick={() => { if (!item.is_read) notificationAPI.markRead(item.id).then(() => updateItem(item.id)); if (item.link?.startsWith("/")) navigate(item.link); }}><b>{item.message}</b><small>{item.created_at ? new Date(item.created_at).toLocaleString("en-IN") : ""}</small></button><div>{!item.is_read && <button onClick={() => notificationAPI.markRead(item.id).then(() => updateItem(item.id))}>Mark read</button>}<button onClick={() => notificationAPI.delete(item.id).then(() => { reload(); toast.success("Notification removed"); })}>Delete</button></div></article>)}{!data.items.length && <div className="account-empty">No notifications yet.</div>}</div></>;
}

function Security({ logout, toast }) {
  const [modal, setModal] = useState(null); const [saving, setSaving] = useState(false); const [password, setPassword] = useState({ current_password: "", new_password: "", confirm: "" }); const [deletion, setDeletion] = useState({ current_password: "", confirmation: "", reason: "" });
  const change = async event => { event.preventDefault(); if (password.new_password !== password.confirm) { toast.error("New passwords do not match"); return; } setSaving(true); try { await authAPI.changePassword({ current_password: password.current_password, new_password: password.new_password }); toast.success("Password changed successfully"); setModal(null); setPassword({ current_password: "", new_password: "", confirm: "" }); } catch (error) { toast.error(error.response?.data?.detail || "Could not change password"); } finally { setSaving(false); } };
  const remove = async event => { event.preventDefault(); setSaving(true); try { await authAPI.deleteAccount(deletion); toast.success("Account deleted"); logout(); } catch (error) { toast.error(error.response?.data?.detail || "Could not delete account"); } finally { setSaving(false); } };
  return <><Title eyebrow="SECURITY">Login & security</Title><p className="account-intro">Manage your password and account access. Sensitive forms open only when you choose an action.</p><div className="security-actions"><article><span className="security-icon">•••</span><div><h2>Password</h2><p>Change your password after confirming the current one.</p></div><button onClick={() => setModal("password")}>Change password</button></article><article className="danger"><span className="security-icon">!</span><div><h2>Delete account</h2><p>Deactivate your account and revoke active access. Procurement history is retained for integrity.</p></div><button onClick={() => setModal("delete")}>Delete account</button></article></div>{modal === "password" && <Modal title="Change password" onClose={() => !saving && setModal(null)}><form className="modal-form" onSubmit={change}><label><span>Current password</span><input required type="password" autoComplete="current-password" value={password.current_password} onChange={e => setPassword({ ...password, current_password: e.target.value })} /></label><label><span>New password</span><input required minLength={8} type="password" autoComplete="new-password" value={password.new_password} onChange={e => setPassword({ ...password, new_password: e.target.value })} /></label><label><span>Confirm new password</span><input required type="password" autoComplete="new-password" value={password.confirm} onChange={e => setPassword({ ...password, confirm: e.target.value })} /></label><div className="modal-actions"><button type="button" onClick={() => setModal(null)}>Cancel</button><button className="primary-action" disabled={saving}>{saving ? "Updating…" : "Update password"}</button></div></form></Modal>}{modal === "delete" && <Modal title="Delete buyer account" danger onClose={() => !saving && setModal(null)}><form className="modal-form" onSubmit={remove}><p>This action deactivates your account and signs you out. It cannot be undone from this screen.</p><label><span>Current password</span><input required type="password" value={deletion.current_password} onChange={e => setDeletion({ ...deletion, current_password: e.target.value })} /></label><label><span>Type DELETE to confirm</span><input required value={deletion.confirmation} onChange={e => setDeletion({ ...deletion, confirmation: e.target.value })} /></label><label><span>Why are you leaving? (optional)</span><textarea maxLength={500} value={deletion.reason} onChange={e => setDeletion({ ...deletion, reason: e.target.value })} /></label><div className="modal-actions"><button type="button" onClick={() => setModal(null)}>Keep my account</button><button className="danger-action" disabled={saving || deletion.confirmation !== "DELETE"}>{saving ? "Deleting…" : "Delete my account"}</button></div></form></Modal>}</>;
}
