import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import MarketplaceHeader from "../components/MarketplaceHeader";
import { conversationAPI } from "../api/api";

export default function MarketplaceMessages() {
  const { id } = useParams(); const navigate = useNavigate(); const [conversations, setConversations] = useState([]); const [active, setActive] = useState(null); const [messages, setMessages] = useState([]); const [body, setBody] = useState(""); const [more, setMore] = useState(false);
  const loadList = () => conversationAPI.list().then(r => { setConversations(r.data); if (!id && r.data[0]) navigate(`/messages/${r.data[0].id}`, { replace: true }); });
  const loadThread = () => { if (!id) return; Promise.all([conversationAPI.detail(id), conversationAPI.messages(id)]).then(([detail, list]) => { setActive(detail.data); setMessages(list.data); conversationAPI.read(id); }); };
  useEffect(() => { loadList(); }, []); useEffect(() => { loadThread(); }, [id]);
  const send = e => { e.preventDefault(); if (!body.trim()) return; conversationAPI.send(id, body).then(r => { setMessages(items => [...items, r.data]); setBody(""); loadList(); }); };
  return <div className="market-page messages-page"><MarketplaceHeader compact /><main className="messages-shell"><aside className="conversation-list"><h1>Messages</h1>{conversations.map(item => <button className={String(item.id) === String(id) ? "active" : ""} onClick={() => navigate(`/messages/${item.id}`)} key={item.id}><span>{item.counterpart_name?.[0]}</span><div><b>{item.counterpart_name}</b><small>{item.request_title}</small><p>{item.last_message || "Conversation ready"}</p></div>{item.unread_count > 0 && <em>{item.unread_count}</em>}</button>)}{!conversations.length && <div className="account-empty">No matched-bid conversations yet.</div>}</aside><section className="thread-panel">{active ? <><header><div><span>{active.counterpart_name?.[0]}</span><div><b>{active.counterpart_name}</b><small>{active.counterpart_location || "Location not shared"} · {active.bid_status}</small></div></div><div className="thread-actions"><button onClick={() => setMore(v => !v)}>Safety & contact ⋮</button>{more && <div><b>{active.counterpart_email}</b>{active.counterpart_phone && <span>{active.counterpart_phone}</span>}<button onClick={() => (active.blocked_by_me ? conversationAPI.unblock(id) : conversationAPI.block(id)).then(loadThread)}>{active.blocked_by_me ? "Unblock" : "Block"}</button><button onClick={() => { const reason = window.prompt("Report reason: spam, harassment, fraud, inappropriate, privacy, or other"); if (reason) conversationAPI.report(id, { reason, details: "Reported from conversation" }); }}>Report</button></div>}</div></header><div className="thread-context"><b>{active.request_title}</b><span>Matched quote conversation · contacts are visible only to participants</span></div><div className="message-stream">{messages.map(message => <div className={message.mine ? "mine" : "theirs"} key={message.id}><p>{message.body}</p><small>{new Date(message.created_at).toLocaleString()}</small></div>)}</div><form className="message-composer" onSubmit={send}><textarea disabled={active.is_blocked} value={body} onChange={e => setBody(e.target.value)} placeholder={active.is_blocked ? "Messaging is blocked" : "Write a message…"} /><button disabled={active.is_blocked}>Send</button></form></> : <div className="thread-empty"><strong>Select a conversation</strong><p>Messaging becomes available when a vendor submits a bid.</p></div>}</section></main></div>;
}
