import { useEffect, useRef, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { buyerAPI, marketplaceAPI, resolveMediaUrl } from "../api/api";
import MarketplaceHeader from "../components/MarketplaceHeader";
import MarketplaceServiceCard, { servicePrice } from "../components/MarketplaceServiceCard";
import { useAuth } from "../context/AuthContext";
import { useToast } from "../context/ToastContext";

export default function ServiceDetail() {
  const { id } = useParams(); const navigate = useNavigate(); const { user } = useAuth(); const toast = useToast();
  const [service, setService] = useState(null); const [reviews, setReviews] = useState({ reviews: [], total_reviews: 0, average_rating: 0 }); const [similar, setSimilar] = useState([]); const [eligibility, setEligibility] = useState(null); const [saved, setSaved] = useState(false); const [saving, setSaving] = useState(false); const [cooldown, setCooldown] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [reviewForm, setReviewForm] = useState({ rating: 5, review: "" }); const [reviewSaving, setReviewSaving] = useState(false); const timer = useRef();
  const load = () => { setLoading(true); setError(""); Promise.all([marketplaceAPI.getService(id), marketplaceAPI.reviews(id), marketplaceAPI.similar(id)]).then(([detail, reviewData, similarData]) => { setService(detail.data); setReviews(reviewData.data); setSimilar(similarData.data?.items || []); }).catch(err => setError(err.response?.status === 404 ? "This service is no longer available." : "Could not load this service.")).finally(() => setLoading(false)); };
  useEffect(load, [id]);
  useEffect(() => { if (user?.role !== "buyer") return; Promise.all([buyerAPI.saved(), buyerAPI.reviewEligibility(id)]).then(([savedItems, eligible]) => { setSaved(savedItems.data.some(item => item.target_type === "service" && item.target_id === Number(id))); setEligibility(eligible.data); if (eligible.data.review) setReviewForm({ rating: eligible.data.review.rating, review: eligible.data.review.review }); }).catch(() => {}); }, [id, user]);
  useEffect(() => () => clearTimeout(timer.current), []);
  const toggleSaved = async () => { if (!user) { sessionStorage.setItem("espReturnTo", `/services/${id}`); navigate(`/signin?returnTo=${encodeURIComponent(`/services/${id}`)}`); return; } if (user.role !== "buyer" || saving || cooldown) return; const next = !saved; setSaving(true); try { if (next) await buyerAPI.save({ target_type: "service", target_id: Number(id) }); else await buyerAPI.unsave("service", Number(id)); setSaved(next); toast.success(next ? "Service saved" : "Removed from saved services"); setCooldown(true); timer.current = setTimeout(() => setCooldown(false), 2000); } catch (err) { toast.error(err.response?.data?.detail || "Could not update saved service"); } finally { setSaving(false); } };
  const request = () => { const intent = { version: 1, service_id: service.id, vendor_id: service.vendor?.id, title: service.title, category: service.category, created_at: Date.now() }; sessionStorage.setItem("espServiceIntent", JSON.stringify(intent)); if (user?.role === "buyer") navigate(`/account/rfps?new=1&service=${service.id}`); else { sessionStorage.setItem("espReturnTo", `/services/${service.id}`); navigate(`/signin?returnTo=${encodeURIComponent(`/services/${service.id}`)}`); } };
  const submitReview = async event => { event.preventDefault(); setReviewSaving(true); try { await buyerAPI.reviewService(id, reviewForm); toast.success(eligibility?.review ? "Review updated" : "Review published"); const [reviewData, eligible] = await Promise.all([marketplaceAPI.reviews(id), buyerAPI.reviewEligibility(id)]); setReviews(reviewData.data); setEligibility(eligible.data); } catch (err) { toast.error(err.response?.data?.detail || "Could not publish review"); } finally { setReviewSaving(false); } };
  if (loading) return <div className="market-page"><MarketplaceHeader compact /><main className="service-detail-shell"><div className="service-detail-image skeleton" /><div className="service-detail-loading"><i className="page-spinner" /><b>Loading service details…</b></div></main></div>;
  if (error || !service) return <div className="market-page"><MarketplaceHeader compact /><div className="service-detail-empty"><strong>{error}</strong><button onClick={() => navigate("/")}>Back to marketplace</button></div></div>;
  const price = servicePrice(service);
  return <div className="market-page service-detail-page"><MarketplaceHeader compact /><main>
    <section className="service-detail-shell"><div className="service-detail-gallery"><div className="service-detail-image">{service.image_url ? <img src={resolveMediaUrl(service.image_url)} alt={`${service.title} catalogue`} /> : <div className="catalogue-placeholder"><span>e</span><b>Image being prepared</b></div>}</div><div className="detail-trust-row"><span>Verified provider</span><span>Vendor-published details</span><span>Direct enquiry</span></div></div><div className="service-detail-copy"><span className="service-detail-category">{service.category}</span><h1>{service.title}</h1>{reviews.total_reviews > 0 && <div className="detail-rating"><b>{reviews.average_rating} ★</b><span>{reviews.total_reviews} verified review{reviews.total_reviews === 1 ? "" : "s"}</span></div>}<p>{service.description}</p><div className="service-detail-vendor"><b>{service.vendor?.organization_name}</b><span>✓ Verified vendor</span>{service.vendor?.location && <small>Serving from {service.vendor.location}</small>}</div>{service.vendor?.vci_credential && <div className="service-detail-vci">VCI verified · {service.vendor.vci_credential.composite_score} · {service.vendor.vci_credential.maturity_band}</div>}<div className="service-detail-price"><small>{service.offer_active ? "Current vendor offer" : price.label}</small><strong>{price.current}</strong>{service.unit && <span>per {service.unit}</span>}{price.original && <del>{price.original}</del>}</div><div className="detail-actions"><button className="service-detail-cta" onClick={request}>Request this service</button><button className={`detail-save ${saved ? "saved" : ""}`} disabled={saving || cooldown} onClick={toggleSaved}>{saving ? <><i className="button-spinner dark" /> Saving…</> : saved ? "♥ Saved" : "♡ Save service"}</button></div><small className="service-detail-note">This starts a vendor enquiry. It is not an order or payment.</small></div></section>
    <section className="detail-information"><article><span>ABOUT THIS SERVICE</span><h2>What the vendor provides</h2><p>{service.description}</p><dl><div><dt>Category</dt><dd>{service.category}</dd></div><div><dt>Provider</dt><dd>{service.vendor?.organization_name}</dd></div><div><dt>Service region</dt><dd>{service.vendor?.location || "Discuss with vendor"}</dd></div><div><dt>Pricing basis</dt><dd>{service.unit ? `Per ${service.unit}` : "Vendor quote"}</dd></div></dl></article><aside><b>Need a tailored scope?</b><p>Create a requirement with quantities, delivery region, timeline, and impact needs. The vendor can reply with a matched quote.</p><button onClick={request}>Create requirement</button></aside></section>
    <section className="service-reviews-section"><div className="detail-section-heading"><div><span>BUYER FEEDBACK</span><h2>Verified service reviews</h2><p>Only buyers with an awarded or completed engagement can review this service.</p></div>{reviews.total_reviews > 0 && <strong>{reviews.average_rating}<small>out of 5</small></strong>}</div>{user?.role === "buyer" && eligibility?.eligible && <form className="review-form" onSubmit={submitReview}><h3>{eligibility.review ? "Update your review" : "Review your engagement"}</h3><div className="review-stars" aria-label="Rating">{[1,2,3,4,5].map(value => <button type="button" className={value <= reviewForm.rating ? "active" : ""} key={value} onClick={() => setReviewForm({ ...reviewForm, rating: value })}>★</button>)}</div><textarea required minLength={10} maxLength={1500} value={reviewForm.review} onChange={e => setReviewForm({ ...reviewForm, review: e.target.value })} placeholder="Share specific, useful feedback about delivery and service quality." /><button className="primary-action" disabled={reviewSaving}>{reviewSaving ? "Publishing…" : eligibility.review ? "Update review" : "Publish review"}</button></form>}{user?.role === "buyer" && eligibility && !eligibility.eligible && <div className="review-locked">✓ Reviews are limited to verified engagements. Complete an awarded requirement for this service to contribute.</div>}<div className="reviews-list">{reviews.reviews.map(review => <article key={review.id}><div className="review-score">{review.rating} ★</div><div><b>{review.reviewer_name}</b><span>✓ Verified engagement</span><p>{review.review}</p><small>{new Date(review.created_at).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })}</small></div></article>)}{!reviews.reviews.length && <div className="account-empty">No verified service reviews yet.</div>}</div></section>
    {similar.length > 0 && <section className="similar-services"><div className="section-heading"><div><span className="eyebrow-commerce">MORE IN {service.category?.toUpperCase()}</span><h2>Similar services</h2></div><button onClick={() => navigate(`/search?category=${encodeURIComponent(service.category)}`)}>View all →</button></div><div className="service-grid">{similar.map(item => <MarketplaceServiceCard key={item.id} service={item} />)}</div></section>}
  </main></div>;
}
