import { useEffect, useRef, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { marketplaceAPI } from "../api/api";
import { useAuth } from "../context/AuthContext";

const RECOMMENDED = ["Corporate gifts", "Office catering", "Last-mile delivery", "Workplace healthcare"];
export function MarketplaceLogo() { return <div className="market-logo" aria-label="Even Procurement"><span className="market-logo-mark"><span>e</span></span><span><strong>even</strong><small>PROCUREMENT</small></span></div>; }

export default function MarketplaceHeader({ initialQuery = "", compact = false }) {
  const navigate = useNavigate(); const location = useLocation(); const { user, logout } = useAuth();
  const [query, setQuery] = useState(initialQuery); const [suggestions, setSuggestions] = useState([]); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(false); const [active, setActive] = useState(-1); const [menuOpen, setMenuOpen] = useState(false); const timer = useRef();
  useEffect(() => setQuery(initialQuery), [initialQuery]); useEffect(() => () => clearTimeout(timer.current), []);
  const choices = query.trim().length < 2 ? RECOMMENDED.map(label => ({ label, subtitle: "Recommended search", query: label, type: "recommended" })) : suggestions;
  const change = value => { setQuery(value); setActive(-1); clearTimeout(timer.current); if (value.trim().length < 2) { setSuggestions([]); setLoading(false); return; } setLoading(true); timer.current = setTimeout(() => marketplaceAPI.suggestions(value.trim()).then(r => setSuggestions(r.data?.items || [])).catch(() => setSuggestions([])).finally(() => setLoading(false)), 180); };
  const submit = (event, value = query) => { event?.preventDefault(); const clean = value.trim(); if (!clean) return; setOpen(false); navigate(`/search?q=${encodeURIComponent(clean)}`); };
  const keyDown = event => { if (event.key === "Escape") { setOpen(false); return; } if (!open || !choices.length) return; if (event.key === "ArrowDown") { event.preventDefault(); setActive(value => (value + 1) % choices.length); } if (event.key === "ArrowUp") { event.preventDefault(); setActive(value => value <= 0 ? choices.length - 1 : value - 1); } if (event.key === "Enter" && active >= 0) { event.preventDefault(); submit(null, choices[active].query); } };
  const signIn = () => { const returnTo = `${location.pathname}${location.search}`; sessionStorage.setItem("espReturnTo", returnTo); navigate(`/signin?returnTo=${encodeURIComponent(returnTo)}`); };
  return <header className={`market-header ${compact ? "compact" : ""}`}><div className="market-header-inner"><button className="logo-button" onClick={() => navigate("/")}><MarketplaceLogo /></button><form className="header-market-search" onSubmit={submit}><span aria-hidden="true">⌕</span><input value={query} onChange={e => change(e.target.value)} onFocus={() => setOpen(true)} onBlur={() => setTimeout(() => setOpen(false), 120)} onKeyDown={keyDown} placeholder="Search for services, vendors or categories" aria-label="Search marketplace" aria-expanded={open} aria-controls="header-search-suggestions" />{open && <div className="market-suggestions" id="header-search-suggestions">{loading ? <div className="suggestion-status"><i className="button-spinner dark" /> Finding services…</div> : <>{query.trim().length < 2 && <div className="suggestion-label">Recommended searches</div>}{choices.length ? choices.map((item, index) => <button type="button" className={active === index ? "active" : ""} key={`${item.type}-${item.id || item.label}-${index}`} onMouseDown={() => submit(null, item.query)}><span><b>{item.label}</b><small>{item.subtitle}</small></span><em>{item.type}</em></button>) : <div className="suggestion-status">No direct suggestion. Press Enter to search all services.</div>}</>}</div>}</form><nav className="market-nav"><button onClick={() => navigate("/search")}>Explore</button>{user?.role === "buyer" && <button onClick={() => navigate("/account/rfps")}>My RFPs</button>}{user?.role === "vendor" && <button onClick={() => navigate("/dashboard")}>Vendor workspace</button>}</nav><div className="market-actions">{!user ? <><button className="sign-in-link" onClick={signIn}>Buyer sign in</button><button className="vendor-cta" onClick={() => navigate("/vendor/register")}>Become a vendor</button></> : <div className="account-menu-wrap"><button className="account-trigger" onClick={() => setMenuOpen(value => !value)} aria-expanded={menuOpen}><span>{user.name?.[0]?.toUpperCase() || "A"}</span><span><small>Hello,</small><b>{user.name?.split(" ")[0]}</b></span><i>⌄</i></button>{menuOpen && <div className="account-menu"><div className="account-menu-head"><b>{user.name}</b><small>{user.email}</small></div>{user.role === "buyer" ? <><button onClick={() => navigate("/account")}>My account</button><button onClick={() => navigate("/account/rfps")}>My RFPs</button><button onClick={() => navigate("/account/quotes")}>Quotes received</button><button onClick={() => navigate("/account/saved")}>Saved services</button><button onClick={() => navigate("/messages")}>Messages</button><button onClick={() => navigate("/account/addresses")}>Addresses</button></> : <button onClick={() => navigate("/dashboard")}>Open workspace</button>}<button className="account-logout" onClick={logout}>Sign out</button></div>}</div>}</div></div></header>;
}
